/**
 * PDP-3 B4 — preview-confirm gate tests.
 *
 * Covers the new `awaiting_push_confirm` stage and the
 * `confirmPush` / `cancelPush` orchestrator methods:
 *   - Gate is on by default (AUTO_PUSH_AFTER_PROTO=false): Proto runs in
 *     dryRun mode, scaffold lands in protoOutput, pipeline halts.
 *   - Confirm: cached files are pushed via pushScaffoldFiles (no LLM
 *     regeneration), pipeline transitions to trace_testing → completed.
 *   - Cancel: pipeline transitions to completed_partial; protoOutput is
 *     preserved so the user can still inspect / copy the code.
 *   - Auto-push override (AUTO_PUSH_AFTER_PROTO=true): the gate is bypassed
 *     and the legacy flow is preserved.
 *   - Idempotency: double-clicking Confirm/Cancel is safe.
 *   - Stage rejection: confirmPush / cancelPush only accept the gate stage.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';

// Gate is the DEFAULT (no env var needed) — but be explicit so a stray
// developer .env value doesn't flip behaviour mid-suite.
process.env.AUTO_PUSH_AFTER_PROTO = 'false';

import {
  PipelineOrchestrator,
  type PipelineStore,
  type PipelineStateUpdate,
  type PipelineEvent,
} from '../../src/pipeline/core/orchestrator/PipelineOrchestrator.js';
import type {
  PipelineState,
  PipelineStage,
  ScribeOutput,
  StructuredSpec,
  ProtoOutput,
  TraceOutput,
} from '../../src/pipeline/core/contracts/PipelineTypes.js';
import type { ScribeAgent, ScribeState } from '../../src/pipeline/agents/scribe/ScribeAgent.js';
import type { ProtoAgent, ProtoResult } from '../../src/pipeline/agents/proto/ProtoAgent.js';
import type { TraceAgent } from '../../src/pipeline/agents/trace/TraceAgent.js';
import { __clearEnvCacheForTests } from '../../src/config/env.js';

__clearEnvCacheForTests();

// ─── Fixtures ────────────────────────────────────

const validSpec: StructuredSpec = {
  title: 'Todo App',
  problemStatement: 'Görev takip uygulaması.',
  userStories: [{ persona: 'Kullanıcı', action: 'Görev oluştur', benefit: 'Takip' }],
  acceptanceCriteria: [{ id: 'ac-1', given: 'Açık', when: 'Ekle', then: 'Görünür' }],
  technicalConstraints: { stack: 'React + Vite' },
  outOfScope: [],
};

const mockScribeOutput: ScribeOutput = {
  spec: validSpec,
  rawMarkdown: '# Todo App',
  confidence: 0.85,
  clarificationsAsked: 0,
};

// Files generated by Proto's dryRun — these are the ones the user inspects
// in the inline preview and then confirms.
const mockProtoFiles: ProtoOutput['files'] = [
  {
    filePath: 'src/App.tsx',
    content: 'export default function App(){return null}',
    linesOfCode: 1,
  },
  { filePath: 'package.json', content: '{"name":"todo"}', linesOfCode: 1 },
];

const dryRunProtoOutput: ProtoOutput = {
  ok: true,
  branch: 'dry-run',
  repo: 'testuser/todo-app',
  repoUrl: 'https://github.com/testuser/todo-app',
  files: mockProtoFiles,
  setupCommands: ['npm install'],
  metadata: { filesCreated: 2, totalLinesOfCode: 2, stackUsed: 'React + Vite', committed: false },
};

const pushedProtoOutput: ProtoOutput = {
  ...dryRunProtoOutput,
  branch: 'main',
  metadata: { ...dryRunProtoOutput.metadata, committed: true },
};

const mockTraceOutput: TraceOutput = {
  ok: true,
  testFiles: [{ filePath: 'tests/e2e/todo.spec.ts', content: 'test()', testCount: 1 }],
  coverageMatrix: { 'ac-1': ['tests/e2e/todo.spec.ts'] },
  testSummary: {
    totalTests: 1,
    coveragePercentage: 100,
    coveredCriteria: ['ac-1'],
    uncoveredCriteria: [],
  },
  branch: 'trace/tests-456',
};

// ─── In-Memory Store ─────────────────────────────

class InMemoryStore implements PipelineStore {
  private pipelines = new Map<string, PipelineState>();

  async create(userId: string): Promise<PipelineState> {
    const id = crypto.randomUUID();
    const pipeline: PipelineState = {
      id,
      userId,
      stage: 'scribe_generating',
      scribeConversation: [],
      traceEnabled: true,
      metrics: { startedAt: new Date(), clarificationRounds: 0, retryCount: 0 },
      createdAt: new Date(),
      updatedAt: new Date(),
      attemptCount: 0,
      stageVersion: 0,
    };
    this.pipelines.set(id, pipeline);
    return { ...pipeline };
  }

  async getById(id: string): Promise<PipelineState | null> {
    const p = this.pipelines.get(id);
    return p ? { ...p } : null;
  }

  async listByUser(userId: string): Promise<PipelineState[]> {
    return [...this.pipelines.values()].filter((p) => p.userId === userId).map((p) => ({ ...p }));
  }

  async update(id: string, data: Partial<PipelineStateUpdate>): Promise<PipelineState> {
    const existing = this.pipelines.get(id);
    if (!existing) throw new Error(`Pipeline not found: ${id}`);
    const updated: PipelineState = {
      ...existing,
      ...data,
      metrics: data.metrics ? { ...existing.metrics, ...data.metrics } : existing.metrics,
      updatedAt: new Date(),
    } as PipelineState;
    if (data.error === null) updated.error = undefined;
    this.pipelines.set(id, updated);
    return { ...updated };
  }
}

// ─── Helpers ────────────────────────────────────

async function waitForStage(
  store: PipelineStore,
  id: string,
  targetStages: PipelineStage[],
  timeoutMs = 5000
): Promise<PipelineState> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const p = await store.getById(id);
    if (p && targetStages.includes(p.stage)) return p;
    await new Promise((r) => setTimeout(r, 10));
  }
  const p = await store.getById(id);
  throw new Error(`Timeout: expected ${targetStages.join('|')}, got ${p?.stage}`);
}

// ─── Mock Factories ─────────────────────────────

function createMockScribe(): ScribeAgent {
  return {
    createInitialState() {
      return {
        idea: 'todo',
        conversation: [],
        clarificationRound: 0,
        phase: 'clarifying' as const,
        pendingQuestionIds: [],
        answeredQuestionIds: [],
      };
    },
    analyzIdea: async () => ({ type: 'spec' as const, data: mockScribeOutput }),
    processUserAnswer(_state: ScribeState, _answer: string) {},
    continueAfterAnswer: async () => ({ type: 'spec' as const, data: mockScribeOutput }),
    regenerateSpec: async () => ({ type: 'spec' as const, data: mockScribeOutput }),
    generateSpec: async () => ({ type: 'spec' as const, data: mockScribeOutput }),
  } as unknown as ScribeAgent;
}

function createMockProto(opts?: {
  execute?: (input: unknown) => Promise<ProtoResult>;
  pushScaffoldFiles?: (...args: unknown[]) => Promise<ProtoResult>;
}): ProtoAgent {
  return {
    execute:
      opts?.execute ??
      (async (input: { dryRun?: boolean }) => {
        // Echo whatever Proto would return — committed:false when dryRun
        // mirrors the real dryRun path in ProtoAgent.execute.
        if (input.dryRun) {
          return { type: 'output' as const, data: dryRunProtoOutput };
        }
        return { type: 'output' as const, data: pushedProtoOutput };
      }),
    pushScaffoldFiles:
      opts?.pushScaffoldFiles ??
      (async () => ({ type: 'output' as const, data: pushedProtoOutput })),
  } as unknown as ProtoAgent;
}

function createMockTrace(opts?: {
  execute?: (input: unknown) => Promise<{ type: 'output'; data: TraceOutput }>;
}): TraceAgent {
  return {
    execute: opts?.execute ?? (async () => ({ type: 'output' as const, data: mockTraceOutput })),
  } as unknown as TraceAgent;
}

function createOrchestrator(overrides?: {
  store?: PipelineStore;
  proto?: ProtoAgent;
  trace?: TraceAgent;
  emit?: (event: PipelineEvent) => void;
}) {
  const store = overrides?.store ?? new InMemoryStore();
  return {
    store,
    orchestrator: new PipelineOrchestrator(
      store,
      createMockScribe(),
      overrides?.proto ?? createMockProto(),
      overrides?.trace ?? createMockTrace(),
      async () => 'testuser',
      async () => 'ghp_mock_token',
      () => ({
        createRepository: async (_o: string, name: string) => ({
          url: `https://github.com/test/${name}`,
        }),
        createBranch: async () => {},
        commitFile: async () => {},
        pushFiles: async () => {},
        createPR: async () => ({ url: '' }),
        listFiles: async () => [] as string[],
        getFileContent: async () => '',
      }),
      overrides?.emit
    ),
  };
}

// ─── Gate ON (default): scaffold → awaiting_push_confirm ──

describe('B4 Preview Gate — gate ON (default)', () => {
  it('halts at awaiting_push_confirm after Proto generation (no auto-push)', async () => {
    process.env.AUTO_PUSH_AFTER_PROTO = 'false';
    __clearEnvCacheForTests();

    const executeCalls: Array<{ dryRun?: boolean }> = [];
    const proto = createMockProto({
      execute: async (input: unknown) => {
        executeCalls.push(input as { dryRun?: boolean });
        return { type: 'output' as const, data: dryRunProtoOutput };
      },
    });
    const { orchestrator, store } = createOrchestrator({ proto });

    const started = await orchestrator.startPipeline(
      'user-1',
      { idea: 'React todo app' },
      undefined,
      undefined,
      undefined,
      undefined,
      true /* traceEnabled */
    );
    await waitForStage(store, started.id, ['awaiting_approval']);
    await orchestrator.approveSpec(started.id, 'my-todo', 'private');

    const gated = await waitForStage(store, started.id, ['awaiting_push_confirm']);
    assert.equal(gated.stage, 'awaiting_push_confirm');
    assert.ok(gated.protoOutput, 'protoOutput should be persisted at gate stage');
    // PR-V-spec-artifacts: orchestrator injects docs/PRD.md + docs/TECHNICAL-ANALYSIS.md
    // alongside Proto's 2 scaffold files → 4 cached files total.
    assert.equal(gated.protoOutput?.files.length, 4, 'cached files visible to FE preview');
    const cachedPaths = gated.protoOutput?.files.map((f) => f.filePath) ?? [];
    assert.ok(cachedPaths.includes('docs/PRD.md'));
    assert.ok(cachedPaths.includes('docs/TECHNICAL-ANALYSIS.md'));
    assert.equal(executeCalls.length, 1);
    assert.equal(executeCalls[0]?.dryRun, true, 'Proto must be called with dryRun:true');
  });

  // PR-F2 (2026-05-19) — Trace must run BEFORE awaiting_push_confirm.
  it('runs Trace in dryRun mode BEFORE awaiting_push_confirm (PR-F2)', async () => {
    process.env.AUTO_PUSH_AFTER_PROTO = 'false';
    __clearEnvCacheForTests();

    const traceCalls: Array<{
      dryRun?: boolean;
      inputFiles?: Array<{ filePath: string; content: string }>;
      repo?: string;
    }> = [];
    const trace = createMockTrace({
      execute: async (input: unknown) => {
        const i = input as {
          dryRun?: boolean;
          inputFiles?: Array<{ filePath: string; content: string }>;
          repo?: string;
        };
        traceCalls.push({ dryRun: i.dryRun, inputFiles: i.inputFiles, repo: i.repo });
        return { type: 'output' as const, data: mockTraceOutput };
      },
    });
    const { orchestrator, store } = createOrchestrator({ trace });

    const started = await orchestrator.startPipeline(
      'user-1',
      { idea: 'React todo app' },
      undefined,
      undefined,
      undefined,
      undefined,
      true /* traceEnabled */
    );
    await waitForStage(store, started.id, ['awaiting_approval']);
    await orchestrator.approveSpec(started.id, 'my-todo', 'private');

    const gated = await waitForStage(store, started.id, ['awaiting_push_confirm']);
    assert.equal(gated.stage, 'awaiting_push_confirm');
    // Trace MUST have run exactly once, in dryRun mode, with Proto's
    // local inputFiles (no GitHub fetch).
    assert.equal(traceCalls.length, 1, 'Trace runs once BEFORE the push gate');
    assert.equal(traceCalls[0]?.dryRun, true, 'Trace called with dryRun:true');
    // PR-V-spec-artifacts: Trace inputFiles now also include the injected
    // docs/PRD.md + docs/TECHNICAL-ANALYSIS.md artifacts (2 source + 2 docs).
    assert.ok(
      traceCalls[0]?.inputFiles && traceCalls[0].inputFiles.length === 4,
      "Trace receives Proto's in-memory files (incl. injected docs/*) as inputFiles"
    );
    assert.ok(gated.traceOutput, 'traceOutput persisted at push gate');
    assert.equal(
      gated.traceOutput?.testSummary?.coveragePercentage,
      100,
      'AC coverage visible at gate stage'
    );
  });

  it('cancelPush → completed_partial; protoOutput stays for inspection', async () => {
    process.env.AUTO_PUSH_AFTER_PROTO = 'false';
    __clearEnvCacheForTests();

    const { orchestrator, store } = createOrchestrator();
    const started = await orchestrator.startPipeline(
      'user-1',
      { idea: 'React todo app' },
      undefined,
      undefined,
      undefined,
      undefined,
      true /* traceEnabled */
    );
    await waitForStage(store, started.id, ['awaiting_approval']);
    await orchestrator.approveSpec(started.id, 'my-todo', 'private');
    await waitForStage(store, started.id, ['awaiting_push_confirm']);

    const cancelled = await orchestrator.cancelPush(started.id);
    assert.equal(cancelled.stage, 'completed_partial');
    assert.ok(cancelled.protoOutput, 'protoOutput preserved so user can still copy files');
    // PR-V-spec-artifacts: 2 source + 2 injected doc artifacts.
    assert.equal(cancelled.protoOutput?.files.length, 4);
  });

  it('confirmPush → pushScaffoldFiles → completed (Trace already ran pre-gate, PR-F2)', async () => {
    process.env.AUTO_PUSH_AFTER_PROTO = 'false';
    __clearEnvCacheForTests();

    const pushCalls: Array<{ owner: string; repo: string; fileCount: number }> = [];
    const proto = createMockProto({
      execute: async () => ({ type: 'output' as const, data: dryRunProtoOutput }),
      pushScaffoldFiles: async (...args: unknown[]) => {
        const [owner, repo, , files] = args as [string, string, unknown, ProtoOutput['files']];
        pushCalls.push({ owner, repo, fileCount: files.length });
        return { type: 'output' as const, data: pushedProtoOutput };
      },
    });
    // PR-F2: count Trace calls so we can prove Trace runs ONCE (pre-gate)
    // and is not invoked again after the user confirms the push.
    const traceCalls: Array<{ dryRun?: boolean }> = [];
    const trace = createMockTrace({
      execute: async (input: unknown) => {
        traceCalls.push(input as { dryRun?: boolean });
        return { type: 'output' as const, data: mockTraceOutput };
      },
    });
    const { orchestrator, store } = createOrchestrator({ proto, trace });

    const started = await orchestrator.startPipeline(
      'user-1',
      { idea: 'React todo app' },
      undefined,
      undefined,
      undefined,
      undefined,
      true /* traceEnabled */
    );
    await waitForStage(store, started.id, ['awaiting_approval']);
    await orchestrator.approveSpec(started.id, 'my-todo', 'private');
    await waitForStage(store, started.id, ['awaiting_push_confirm']);

    // Sanity: Trace already ran in dryRun BEFORE the gate.
    assert.equal(traceCalls.length, 1, 'Trace runs once pre-gate in dryRun mode');
    assert.equal(traceCalls[0]?.dryRun, true);

    await orchestrator.confirmPush(started.id);
    const completed = await waitForStage(store, started.id, ['completed']);
    assert.equal(completed.stage, 'completed');
    assert.equal(pushCalls.length, 1, 'pushScaffoldFiles called once');
    assert.equal(pushCalls[0]?.owner, 'testuser');
    assert.equal(pushCalls[0]?.repo, 'my-todo');
    // PR-V-spec-artifacts: pushScaffoldFiles receives 2 source + 2 injected docs.
    assert.equal(pushCalls[0]?.fileCount, 4);
    // After push, protoOutput.branch should be the real "main", not "dry-run"
    assert.equal(completed.protoOutput?.branch, 'main');
    // PR-F2: Trace must NOT be invoked again on push confirmation.
    assert.equal(traceCalls.length, 1, 'Trace does NOT run again on confirmPush');
    // The pre-gate traceOutput stays intact.
    assert.ok(completed.traceOutput, 'traceOutput from pre-gate dryRun preserved');
  });

  it('confirmPush is idempotent — second call returns current state', async () => {
    process.env.AUTO_PUSH_AFTER_PROTO = 'false';
    __clearEnvCacheForTests();

    const { orchestrator, store } = createOrchestrator();
    const started = await orchestrator.startPipeline(
      'user-1',
      { idea: 'Todo app' },
      undefined,
      undefined,
      undefined,
      undefined,
      true /* traceEnabled */
    );
    await waitForStage(store, started.id, ['awaiting_approval']);
    await orchestrator.approveSpec(started.id, 'my-todo', 'private');
    await waitForStage(store, started.id, ['awaiting_push_confirm']);

    await orchestrator.confirmPush(started.id);
    // Wait for push to settle then call again
    await waitForStage(store, started.id, ['completed']);
    const second = await orchestrator.confirmPush(started.id);
    assert.equal(second.stage, 'completed', 'idempotent — already past gate');
  });

  it('cancelPush is idempotent on terminal state', async () => {
    process.env.AUTO_PUSH_AFTER_PROTO = 'false';
    __clearEnvCacheForTests();

    const { orchestrator, store } = createOrchestrator();
    const started = await orchestrator.startPipeline(
      'user-1',
      { idea: 'Todo app' },
      undefined,
      undefined,
      undefined,
      undefined,
      true /* traceEnabled */
    );
    await waitForStage(store, started.id, ['awaiting_approval']);
    await orchestrator.approveSpec(started.id, 'my-todo', 'private');
    await waitForStage(store, started.id, ['awaiting_push_confirm']);

    await orchestrator.cancelPush(started.id);
    const second = await orchestrator.cancelPush(started.id);
    assert.equal(second.stage, 'completed_partial');
  });

  it('confirmPush rejected when not at gate stage', async () => {
    process.env.AUTO_PUSH_AFTER_PROTO = 'false';
    __clearEnvCacheForTests();

    const { orchestrator, store } = createOrchestrator();
    const started = await orchestrator.startPipeline(
      'user-1',
      { idea: 'Todo app' },
      undefined,
      undefined,
      undefined,
      undefined,
      true /* traceEnabled */
    );
    await waitForStage(store, started.id, ['awaiting_approval']);
    // Spec not yet approved → still at awaiting_approval, cannot confirmPush
    await assert.rejects(() => orchestrator.confirmPush(started.id), { message: /Invalid stage/ });
  });

  it('cancelPush rejected when not at gate stage', async () => {
    process.env.AUTO_PUSH_AFTER_PROTO = 'false';
    __clearEnvCacheForTests();

    const { orchestrator, store } = createOrchestrator();
    const started = await orchestrator.startPipeline(
      'user-1',
      { idea: 'Todo app' },
      undefined,
      undefined,
      undefined,
      undefined,
      true /* traceEnabled */
    );
    await waitForStage(store, started.id, ['awaiting_approval']);
    await assert.rejects(() => orchestrator.cancelPush(started.id), { message: /Invalid stage/ });
  });

  it('emits stage_change event for awaiting_push_confirm', async () => {
    process.env.AUTO_PUSH_AFTER_PROTO = 'false';
    __clearEnvCacheForTests();

    const events: PipelineEvent[] = [];
    const { orchestrator, store } = createOrchestrator({
      emit: (event) => events.push(event),
    });
    const started = await orchestrator.startPipeline(
      'user-1',
      { idea: 'Todo app' },
      undefined,
      undefined,
      undefined,
      undefined,
      true /* traceEnabled */
    );
    await waitForStage(store, started.id, ['awaiting_approval']);
    await orchestrator.approveSpec(started.id, 'my-todo', 'private');
    await waitForStage(store, started.id, ['awaiting_push_confirm']);

    const stages = events.filter((e) => e.type === 'stage_change').map((e) => e.stage);
    assert.ok(stages.includes('awaiting_push_confirm'), 'gate stage_change event emitted');
  });
});

// ─── Gate OFF (auto-push): legacy flow preserved ─────────

describe('B4 Preview Gate — gate OFF (AUTO_PUSH_AFTER_PROTO=true)', () => {
  it('bypasses gate when env is set, Proto runs without dryRun', async () => {
    process.env.AUTO_PUSH_AFTER_PROTO = 'true';
    __clearEnvCacheForTests();

    const executeCalls: Array<{ dryRun?: boolean }> = [];
    const pushScaffoldCalls: number[] = [];
    const proto = createMockProto({
      execute: async (input: unknown) => {
        executeCalls.push(input as { dryRun?: boolean });
        return { type: 'output' as const, data: pushedProtoOutput };
      },
      pushScaffoldFiles: async () => {
        pushScaffoldCalls.push(1);
        return { type: 'output' as const, data: pushedProtoOutput };
      },
    });
    const { orchestrator, store } = createOrchestrator({ proto });

    const started = await orchestrator.startPipeline(
      'user-1',
      { idea: 'Todo app' },
      undefined,
      undefined,
      undefined,
      undefined,
      true /* traceEnabled */
    );
    await waitForStage(store, started.id, ['awaiting_approval']);
    await orchestrator.approveSpec(started.id, 'my-todo', 'private');

    const completed = await waitForStage(store, started.id, ['completed']);
    assert.equal(completed.stage, 'completed');
    assert.equal(executeCalls.length, 1);
    assert.equal(executeCalls[0]?.dryRun, false, 'auto-push path runs Proto with dryRun:false');
    assert.equal(pushScaffoldCalls.length, 0, 'auto-push path skips pushScaffoldFiles helper');

    // Reset so subsequent tests in other files see the default
    process.env.AUTO_PUSH_AFTER_PROTO = 'false';
    __clearEnvCacheForTests();
  });
});
