/**
 * Default GitHub Actions workflow pushed with Trace-generated Playwright tests.
 * Runs on every push / PR so verification happens in GitHub-hosted runners (not on AKIS VM).
 */
import type { TraceOutput } from '../core/contracts/PipelineTypes.js';

export const AKIS_E2E_WORKFLOW_PATH = '.github/workflows/akis-e2e.yml';

/** YAML content — GitHub expressions use ${{ }} and must not be JS template interpolations */
export function getAkisE2eWorkflowYaml(): string {
  return [
    '# Auto-generated by AKIS Trace — Playwright (+ optional Cucumber) verification',
    '# Do not rename without updating AKIS docs.',
    'name: AKIS E2E',
    '',
    'on:',
    '  push:',
    "    branches: ['**']",
    '  pull_request:',
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  contents: read',
    '',
    'concurrency:',
    '  group: akis-e2e-${{ github.workflow }}-${{ github.ref }}',
    '  cancel-in-progress: true',
    '',
    'jobs:',
    '  playwright:',
    '    name: Playwright E2E',
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 35',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v4',
    '',
    '      - name: Setup Node.js',
    '        uses: actions/setup-node@v4',
    '        with:',
    "          node-version: '20'",
    '',
    '      - name: Install dependencies',
    '        shell: bash',
    '        run: |',
    '          set -euo pipefail',
    '          if [ -f pnpm-lock.yaml ]; then',
    '            npm install -g pnpm@9',
    '            pnpm install --frozen-lockfile || pnpm install',
    '          elif [ -f package-lock.json ]; then',
    '            npm ci',
    '          else',
    '            npm install',
    '          fi',
    '',
    '      - name: Install Playwright browsers',
    '        run: npx playwright install --with-deps chromium',
    '',
    '      - name: Run Playwright tests',
    '        env:',
    '          CI: true',
    '        run: npx playwright test --reporter=github --reporter=line',
    '',
    '      - name: Upload Playwright report',
    '        if: failure()',
    '        uses: actions/upload-artifact@v4',
    '        with:',
    '          name: playwright-report',
    '          path: playwright-report/',
    '          if-no-files-found: ignore',
    '',
    '  cucumber:',
    '    name: Cucumber BDD (optional)',
    '    runs-on: ubuntu-latest',
    "    if: ${{ hashFiles('features/**/*.feature') != '' }}",
    '    timeout-minutes: 20',
    '    continue-on-error: true',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - uses: actions/setup-node@v4',
    '        with:',
    "          node-version: '20'",
    '      - name: Install dependencies',
    '        shell: bash',
    '        run: |',
    '          set -euo pipefail',
    '          if [ -f pnpm-lock.yaml ]; then',
    '            npm install -g pnpm@9',
    '            pnpm install --frozen-lockfile || pnpm install',
    '          elif [ -f package-lock.json ]; then',
    '            npm ci',
    '          else',
    '            npm install',
    '          fi',
    '      - name: Install Cucumber runner',
    '        run: npm install --no-save @cucumber/cucumber@10',
    '      - name: Run Cucumber',
    "        run: npx cucumber-js features --publish-quiet || echo \"::warning::Cucumber run failed — check features/steps\"",
    '',
  ].join('\n');
}

/**
 * Ensures the AKIS CI workflow file is present when Trace pushes tests.
 */
function normalizePath(p: string): string {
  return p.replace(/\\/g, '/');
}

/**
 * Returns true only when this exact workflow file is already in the batch.
 * Other `.github/workflows/*.yml` files do not block adding `akis-e2e.yml`.
 */
export function hasAkisE2eWorkflowInBatch(files: TraceOutput['testFiles']): boolean {
  return files.some((f) => normalizePath(f.filePath) === AKIS_E2E_WORKFLOW_PATH);
}

export function mergeAkisCiWorkflowIntoTestFiles(files: TraceOutput['testFiles']): TraceOutput['testFiles'] {
  if (hasAkisE2eWorkflowInBatch(files)) {
    return files;
  }
  return [
    ...files,
    {
      filePath: AKIS_E2E_WORKFLOW_PATH,
      content: getAkisE2eWorkflowYaml(),
      testCount: 0,
    },
  ];
}
